version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.2.0-browsers
    steps:
      - checkout
      - setup_remote_docker      
      - run:
          name: Prep
          command: |
            # I should maybe be using a different docker image in Circle rather than
            # doing all of this junk, but works for me.  :)
            mkdir -p /tmp/artifacts
            sudo npm install -g yarn
            # Do not install s3cmd from apt-get, it's an out of date version.
            wget https://github.com/s3tools/s3cmd/releases/download/v2.0.2/s3cmd-2.0.2.tar.gz
            tar zxvf s3cmd-2.0.2.tar.gz

            curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
            sudo python get-pip.py
            sudo pip install setuptools

            pip --version            
            
            cd s3cmd-2.0.2 && sudo python setup.py install
            cd $HOME && s3cmd --version

            pip install --upgrade --user awscli
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: |
            npm config set registry https://neo.jfrog.io/neo/api/npm/npm/
            yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run tests
          no_output_timeout: 1200
          command: |
            ls -l src/components/
            # Take careful note of runInBand https://jestjs.io/docs/en/troubleshooting.html#tests-are-extremely-slow-on-docker-and-or-continuous-integration-ci-server
            yarn test --runInBand --coverage --watchAll=false
      - store_artifacts:
            path: coverage
            prefix: coverage      
      - store_artifacts:
            path: /tmp/artifacts
      - store_artifacts:
            path: /home/circleci/.npm
