name: Node.js CI & Deploy

on:
  push:
    branches: [ gcp ]
  pull_request:
    branches: [ gcp ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: echo $service_key > /tmp/service_key.json
      env:
        service_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
    - run: yarn install
    - run: yarn test --runInBand --coverage --watchAll=false
      env:
        CI: true
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/service_key.json

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true
    - run: gcloud info
    - run: gcloud functions deploy cudPubsub --ingress-settings=all --runtime=nodejs10 --allow-unauthenticated --timeout=300 --set-env-vars GOOGLE_PROJECT=${{ secrets.GCP_PROJECT_ID }} --trigger-topic neo4j-cud
    - run: gcloud functions deploy cypherPubsub --ingress-settings=all --runtime=nodejs10 --allow-unauthenticated --timeout=300 --set-env-vars GOOGLE_PROJECT=${{ secrets.GCP_PROJECT_ID }} --trigger-topic cypher
