name: Node.js CI

on:
  push:
    branches: [ gcp ]
  pull_request:
    branches: [ gcp ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: echo $service_key > /tmp/service_key.json
      env:
        service_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
    - run: yarn install
    - run: yarn test --runInBand --coverage --watchAll=false
      env:
        CI: true
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/service_key.json